[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dollarimport"
version = "0.1.0.4"
description = "Enables ${var} syntax in Python using exec and globals"
authors = [{name="Elijah Morgan"}]
readme = "README.md"
requires-python = ">=3.8"
